print("Conversion de clases basica:")
print()
print("Empezamos usando solo la funcion input: ")
ejemplo_string = type(input("Dime un numero: "))
print(ejemplo_string)
print()
print("por lo visto arriba, usando solo input la clase queda en string, por mas que sea un numero")
print("en cambio, usando la funcion int sobre la funcion input , se convertiria de la siguiente manera:  ")
print()
ejemplo_conversion_int = type(int(input("Dime un numero: ")))
print(ejemplo_conversion_int)
